### PR TITLE
Updated to 1.14.1

### PR DESCRIPTION
**Pull request by Shnupbups**

### CODE REVIEW

**Comment by 3TUSK** [comment]
I thought there is backward compatibility for v0 `fabric-mod.json` support?

**Comment by Shnupbups** [comment]
There is, but you shouldn't be using v0 at this point. There's no reason to, and it just makes a warning pop up in the log on load. Whereas v1 provides a bunch of extra info.

**Comment by 3TUSK** [comment]
> you shouldn't be using v0 at this point.

True, except I was busy with many other things, so I haven't migrated it yet.

**Comment by Shnupbups** [comment]
The main part of this PR is the Block Entity Builder change, without which the mod crashes on startup in 1.14.1.

**Comment by Shnupbups** [comment]
Are you going to merge this? Because the mod crashes in 1.14.1 without it...

**Comment by 3TUSK** [comment]
> Because the mod crashes in 1.14.1 without it

*crash*
*triggered*

That is out of my surprise. Give me 24 hours.  
Also I wonder what the crash report looks like.

**Comment by Shnupbups** [comment]
Any mod that adds Block Entities crashes if not updated to 1.14.1 due to changes in the BlockEntityBuilder code. The crash report isn't exactly exhilarating.

**Comment by 3TUSK** [comment]
Manually merged as https://github.com/Team-AbCiv/Dumpster/commit/96a0db1d1ca1d492d3cad8f8164b85eb31891c2f (due to squash merge - I know it looks weird), expect a new release (https://minecraft.curseforge.com/projects/dumpster/files/2714600) being available soon.

**Pull request closed without merging**
